### ISSUE TITLE
Road to next version

### ISSUE THREAD

**Issue by Huluti** [Kilian/Trimage#51]
Now that the software has been ported to Python 3 and Qt5, we can prepare the next version.
I propose to use this issue to list what needs to be done.

Here's my thoughts as they come to me:

- [x] Update the debian folder (maybe with @hosiet as you suggested)
- [x] Choose a version number: 1.0.6?
- [x] Update the website:
    - [x] Update requirements
        - [x] Review needed version of libs
    - [x] Review the installation options
    -  ~~Remove the development branch (wich is outdated)~~
- [x] Update the **website** folder in the repo
- [x] Test the soft to see potential regressions

After these:
- [x] Create a tag with a changelog

Do you see others things?

**Comment by Kilian** [comment]
I want to keep this semantically versioned, so 1.0.6 would be the next version. I could also take a stab at the Debian folder, but it's been a long time since I've packaged anything. 

I'll revise the website shortly. 

I tend to like a development vs. master branch, so I'll just bring development up to date with master.

**Comment by Huluti** [comment]
Any news on your side?

**Comment by Kilian** [comment]
I'll have a look later today for the remaining points and then create a new tag.

**Comment by Kilian** [comment]
Tag created: https://github.com/Kilian/Trimage/releases/tag/1.0.6 I'll check where to ping the debian team about this (@hosiet?)
